version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - postgres
    ports:
      - "8083:8083"
    restart: always
    networks:
      - backend-network

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "brigade"
      POSTGRES_USER: "brigade"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db/001_init_up.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  prometheus:
    hostname: prometheus
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - backend-network

volumes:
  postgres_data: {}

networks:
  backend-network:
    name: "backend-network"
    driver: bridge
